#!/usr/bin/env bash
# 沙箱 pod 入口：1) 由环境变量生成 CODEX_HOME 的 config.toml 与 environments.toml；2) 起沙箱侧桥（回环）；
# 3) 前台起 app-server，监听 ws://0.0.0.0:$APP_SERVER_PORT，能力令牌鉴权（工作台是唯一客户端）。
# 必需环境：RELAY_URL RELAY_USER RELAY_TOKEN APP_SERVER_TOKEN_FILE；模型 key 二选一：OPENAI_API_KEY（含国产厂商 key）或挂好的 $CODEX_HOME/auth.json。
# 可选：MODEL、MODEL_PROVIDER、PROVIDER_BASE_URL、PROVIDER_WIRE_API（默认 responses）、ENVIRONMENT_ID（默认 user-pc）；
#       KNOWLEDGE_MCP_URL + KNOWLEDGE_MCP_TOKEN（知识服务 MCP，0006）。
set -euo pipefail
: "${RELAY_URL:?}" "${RELAY_USER:?}" "${RELAY_TOKEN:?}" "${APP_SERVER_TOKEN_FILE:?}"
CODEX_HOME="${CODEX_HOME:-/data/codex}"; mkdir -p "$CODEX_HOME"
# 老 PVC 里可能留着 containerd 当年为匿名卷建的 root 属主空目录（见 Dockerfile 注释）：不可写就明说退出，别静默写到别处
[ -w "$CODEX_HOME" ] || { echo "[entrypoint] $CODEX_HOME is not writable by $(id -u) (owner $(stat -c %u "$CODEX_HOME")): fix the PVC subdir ownership"; exit 4; }
chmod 700 "$CODEX_HOME" 2>/dev/null || true
ENVIRONMENT_ID="${ENVIRONMENT_ID:-user-pc}"

if [ ! -f "$CODEX_HOME/config.toml" ] || [ "${REWRITE_CONFIG:-1}" = 1 ]; then
  {
    echo "# generated by sandbox entrypoint; do not edit"
    [ -n "${MODEL:-}" ] && echo "model = \"${MODEL}\""
    if [ -n "${MODEL_PROVIDER:-}" ]; then
      echo "model_provider = \"${MODEL_PROVIDER}\""
      echo "[model_providers.${MODEL_PROVIDER}]"
      echo "name = \"${MODEL_PROVIDER}\""
      echo "base_url = \"${PROVIDER_BASE_URL:?PROVIDER_BASE_URL required with MODEL_PROVIDER}\""
      echo "requires_openai_auth = true"
      echo "wire_api = \"${PROVIDER_WIRE_API:-responses}\""
    fi
    # 一条线只有一个 Codex，每一轮都由工作台发起、记账、计费：子代理另起账外的线，「目标」让线自己接着跑，都关掉
    # （工作台在每条线上也会关；这里是沙箱自己的底线，迁移账本 31）
    echo "[features]"
    echo "multi_agent = false"
    echo "goals = false"
    # Windows 执行端（0005-agent，2026-10-08）：编排端按自己这一项决定发给 Windows 执行器的内层沙箱级别，
    # 不配就是 disabled，app-server 在 Windows 环境上一条命令都不发。配 unelevated（不要管理员）；
    # 本地代理在本机有 elevated 环境时自己升级，远端降不了级。对 Linux 执行器这一项没有作用。
    echo "[windows]"
    echo "sandbox = \"unelevated\""
    # 知识服务 MCP（0006）：HTTP 型写进编排端 config；令牌走环境变量名，不落盘（F-KNOW-03）
    if [ -n "${KNOWLEDGE_MCP_URL:-}" ]; then
      echo "[mcp_servers.sunmoon_knowledge]"
      echo "url = \"${KNOWLEDGE_MCP_URL}\""
      echo "bearer_token_env_var = \"SUNMOON_KNOWLEDGE_TOKEN\""
      echo "startup_timeout_sec = 20"
    fi
    # 工作台的记录工具服务（0001-workbench：专家读本项目别的对话与底稿），同一种接法
    if [ -n "${WORKBENCH_MCP_URL:-}" ]; then
      echo "[mcp_servers.sunmoon_workbench]"
      echo "url = \"${WORKBENCH_MCP_URL}\""
      echo "bearer_token_env_var = \"SUNMOON_WORKBENCH_TOKEN\""
      echo "startup_timeout_sec = 20"
    fi
  } > "$CODEX_HOME/config.toml"
fi
# MCP 令牌留在 app-server 进程环境里（它按 bearer_token_env_var 读）；沙箱里的模型进程看不到环境
if [ -n "${KNOWLEDGE_MCP_TOKEN:-}" ]; then export SUNMOON_KNOWLEDGE_TOKEN="$KNOWLEDGE_MCP_TOKEN"; unset KNOWLEDGE_MCP_TOKEN; fi
if [ -n "${WORKBENCH_MCP_TOKEN:-}" ]; then export SUNMOON_WORKBENCH_TOKEN="$WORKBENCH_MCP_TOKEN"; unset WORKBENCH_MCP_TOKEN; fi
# 远端环境：默认指向沙箱侧桥；不含本地执行（include_local=false，C-A12 不退回本地执行）
cat > "$CODEX_HOME/environments.toml" <<EOF
default = "${ENVIRONMENT_ID}"
include_local = false
[[environments]]
id = "${ENVIRONMENT_ID}"
url = "ws://127.0.0.1:${BRIDGE_PORT:-47002}"
EOF
# BYOK：key 以 auth.json 形式落 CODEX_HOME（600），进程环境里不再保留
if [ -n "${OPENAI_API_KEY:-}" ]; then
  umask 077; printf '{"auth_mode":"apikey","OPENAI_API_KEY":"%s"}' "$OPENAI_API_KEY" > "$CODEX_HOME/auth.json"; unset OPENAI_API_KEY
fi
[ -f "$CODEX_HOME/auth.json" ] || { echo "no auth.json and no OPENAI_API_KEY: refusing to start (BYOK is mandatory)"; exit 3; }

echo "[entrypoint] codex $(codex --version) relay=$RELAY_URL user=$RELAY_USER env=$ENVIRONMENT_ID bridge=127.0.0.1:${BRIDGE_PORT:-47002} app-server=0.0.0.0:${APP_SERVER_PORT:-47800}"
CODEX_VERSION="$(codex --version | awk '{print $2}')" RELAY_URL="$RELAY_URL" RELAY_USER="$RELAY_USER" RELAY_TOKEN="$RELAY_TOKEN" BRIDGE_PORT="${BRIDGE_PORT:-47002}" \
  python3 /opt/sandbox/sandbox_bridge.py &
BRIDGE_PID=$!
trap 'kill $BRIDGE_PID 2>/dev/null' EXIT
for i in $(seq 1 40); do python3 -c "import socket;socket.create_connection(('127.0.0.1',${BRIDGE_PORT:-47002}),1).close()" 2>/dev/null && break; sleep 0.25; done
unset RELAY_TOKEN
exec codex app-server --listen "ws://0.0.0.0:${APP_SERVER_PORT:-47800}" --ws-auth capability-token --ws-token-file "$APP_SERVER_TOKEN_FILE"
