#!/usr/bin/env bash
# 沙箱 pod 入口：1) 由环境变量生成 CODEX_HOME 的 config.toml 与 environments.toml；2) 起沙箱侧桥（回环）；
# 3) 前台起 app-server，监听 ws://0.0.0.0:$APP_SERVER_PORT，能力令牌鉴权（工作台是唯一客户端）。
# 必需环境：RELAY_URL RELAY_USER RELAY_TOKEN APP_SERVER_TOKEN_FILE；模型 key 二选一：OPENAI_API_KEY（含国产厂商 key）或挂好的 $CODEX_HOME/auth.json。
# 可选：MODEL、MODEL_PROVIDER、PROVIDER_BASE_URL、PROVIDER_WIRE_API（默认 responses）、ENVIRONMENT_ID（默认 user-pc）。
set -euo pipefail
: "${RELAY_URL:?}" "${RELAY_USER:?}" "${RELAY_TOKEN:?}" "${APP_SERVER_TOKEN_FILE:?}"
CODEX_HOME="${CODEX_HOME:-/data/codex}"; mkdir -p "$CODEX_HOME"; chmod 700 "$CODEX_HOME"
ENVIRONMENT_ID="${ENVIRONMENT_ID:-user-pc}"

if [ ! -f "$CODEX_HOME/config.toml" ] || [ "${REWRITE_CONFIG:-1}" = 1 ]; then
  {
    echo "# generated by sandbox entrypoint; do not edit"
    [ -n "${MODEL:-}" ] && echo "model = \"${MODEL}\""
    if [ -n "${MODEL_PROVIDER:-}" ]; then
      echo "model_provider = \"${MODEL_PROVIDER}\""
      echo "[model_providers.${MODEL_PROVIDER}]"
      echo "name = \"${MODEL_PROVIDER}\""
      echo "base_url = \"${PROVIDER_BASE_URL:?PROVIDER_BASE_URL required with MODEL_PROVIDER}\""
      echo "requires_openai_auth = true"
      echo "wire_api = \"${PROVIDER_WIRE_API:-responses}\""
    fi
  } > "$CODEX_HOME/config.toml"
fi
# 远端环境：默认指向沙箱侧桥；不含本地执行（include_local=false，C-A12 不退回本地执行）
cat > "$CODEX_HOME/environments.toml" <<EOF
default = "${ENVIRONMENT_ID}"
include_local = false
[[environments]]
id = "${ENVIRONMENT_ID}"
url = "ws://127.0.0.1:${BRIDGE_PORT:-47002}"
EOF
# BYOK：key 以 auth.json 形式落 CODEX_HOME（600），进程环境里不再保留
if [ -n "${OPENAI_API_KEY:-}" ]; then
  umask 077; printf '{"auth_mode":"apikey","OPENAI_API_KEY":"%s"}' "$OPENAI_API_KEY" > "$CODEX_HOME/auth.json"; unset OPENAI_API_KEY
fi
[ -f "$CODEX_HOME/auth.json" ] || { echo "no auth.json and no OPENAI_API_KEY: refusing to start (BYOK is mandatory)"; exit 3; }

echo "[entrypoint] codex $(codex --version) relay=$RELAY_URL user=$RELAY_USER env=$ENVIRONMENT_ID bridge=127.0.0.1:${BRIDGE_PORT:-47002} app-server=0.0.0.0:${APP_SERVER_PORT:-47800}"
CODEX_VERSION="$(codex --version | awk '{print $2}')" RELAY_URL="$RELAY_URL" RELAY_USER="$RELAY_USER" RELAY_TOKEN="$RELAY_TOKEN" BRIDGE_PORT="${BRIDGE_PORT:-47002}" \
  python3 /opt/sandbox/sandbox_bridge.py &
BRIDGE_PID=$!
trap 'kill $BRIDGE_PID 2>/dev/null' EXIT
unset RELAY_TOKEN
exec codex app-server --listen "ws://0.0.0.0:${APP_SERVER_PORT:-47800}" --ws-auth capability-token --ws-token-file "$APP_SERVER_TOKEN_FILE"
