apiVersion: v1
kind: Secret
metadata:
  name: ${LLMOPS_SSR_SECRET_NAME}
  namespace: ${NAMESPACE}
  labels:
    app: llmops-app-front
    component: secret
    environment: ${ENVIRONMENT}
    managed-by: deploy-script
type: Opaque
stringData:
  SECRET_KEY: ${SECRET_KEY}
  TOTP_SECRET_KEY: ${TOTP_SECRET_KEY}
  POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
  NEO4J_PASSWORD: ${NEO4J_PASSWORD}
  FIRST_SUPERUSER: ${FIRST_SUPERUSER}
  FIRST_SUPERUSER_PASSWORD: ${FIRST_SUPERUSER_PASSWORD}
  SMTP_USER: ${SMTP_USER:-}
  SMTP_PASSWORD: ${SMTP_PASSWORD:-}
  SENTRY_DSN: ${SENTRY_DSN:-}
