apiVersion: v1
kind: Secret
metadata:
    name: casdoor-config
    namespace: platform-system
stringData:
    app.conf: ENC[AES256_GCM,data:xEh4/v9g8qBlpx4/kdcmoZaE6oYrdygdTFKOw2O0jOBgjz6j/ki/UtFIEgKjYpxcF2kUFoYR7Imp0Bpsb3/TgbbEG1xR2TQ6tI8UVMYNNlW3BaQCOEu4EJzAhxEFt8zuZ2FMdSqj2+WM2k3CBY7DVDi7+fQSkd9JOiao2aKMP6l/9WWxhjnklEAmGvvhTmUp2UANeN4Iz5bdQeYhuuMv0WZ7XX2Voiu5FLCa7/pD3hQ9h3ns5XeTm7iiwQp4WSMpFoWLviJEoZFO8EUrtdwvs2G3DmF2se0RJ7Eg+zNMOwhrk3XOz3Ti+tccWpr0jkKnLCN58+95KJf8O6rER/AOpYpLsFF8pDUqSZ3G7fHMNmPPFa+nmR8La+n23/tN/ytLcjPdIqOTRc9bLKKAAu+R1NNSqxr5Sh1HW/7t4W8QsCp9QxfFpdumNZVAM7nD3TCpBPSKlmRU/YyUgtMGYX7eGijwBcby3EwLXUl9my4/8gInw+PrHQy4o6eBSYK79rtilAJQ7at1FdmXKh7mgBnVwbPbNaYS5XvrshXM1TE3bRvP+SRU1IIApwMmsp1VJb8I2hcyXkWncbGgE4+UbxbQBcbBeQi9x5SMM2sSJY8F1wMmMohTI6UE9XXQ0OzmOsr42kKM26+Y+o4cG93fVjgU,iv:urd3FdgiZvznZ5rOEDzraMUFMYze+7XxsvnGYewEOXA=,tag:jINrJrRYFldUASDLM8UBsA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBldVUxOHRreDlhZHNyQ1cv
            WFB0bUU1dGtuYW5GV1hpdFBwNm5mclptdVI0CmFiVkdXSlcwRlJHU29sRXYxNlh6
            djJxYkxVV3B4T294UFhiUm5TZksvRmMKLS0tIGhYekZYL3BWSGFiSHY2cFI5elA4
            VHg5bTRPRFFkTlBtbzlEa0k3WGhsQU0K1geLi2/NrRNf5kv/kWwMI5Q2rmbgIOwi
            xn5DZujGt0s1RTqULS73RopEK9Bw/RxlNfs8arRHRPBGGIXuOFL2JA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1usl2cz5ltxz7au5tdpjqz7t77nzh3a29dgyewwfexqcctjfp2edq5yy6ge
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-03T03:20:28Z"
    mac: ENC[AES256_GCM,data:LA6FSFime+iT7arrTBSLWAjqybtxua1M3CfG5ifVOp7LrXPjbQnwYkG0AFvSNatISrA8Mc+4eZzEmbcnPPXGwbOD/WRjBi/k4e2RfUOGwh0NUcwHKulIlq5jdlRWaxJufDfP1kDkjJkPCTFmq8cSbxS04J5U/4/UPsBEs3EbG0U=,iv:IEMl1vH32o9gEAPm9m/VBCUQMfHhIdjRQbcicJ3LW6w=,tag:BkuGcC88AJAZ5CHbdaugLA==,type:str]
    version: 3.13.3
