apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: neo4j-stripprefix
  namespace: data-platform-dev
  labels:
    app: data-platform-ingress
    component: neo4j-stripprefix
    project: sunmoonai
spec:
  stripPrefix:
    prefixes:
      - "/neo4j"

