#!/usr/bin/env bash
# Shared component pull-secret lifecycle. Sourcing defines functions only.
# Cloud execution: 未经实机验证. Call after the pure deploy-plan request boundary.
registry_secret_entry() (
    set -euo pipefail
    # Do not expose sourced credentials when a caller enabled shell tracing.
    set +x
    local root="$1" config="$2" contract="$3" default_namespace="$4"
    shift 4
    source "$root/utils/cluster-arg-parser.sh"
    unified_parse_cluster_arg "$@"
    set -- "${PARSED_ARGS[@]}"
    local action=deploy namespace='' positional_namespace=''
    case "$contract" in
        deploy-project)
            [[ $# -le 4 ]] || { echo 'Too many Secret arguments' >&2; return 2; }
            positional_namespace="${2:-}" ;;
        namespace)
            [[ $# -le 3 ]] || { echo 'Expected action namespace dry_run' >&2; return 2; }
            action="${1:-deploy}"; positional_namespace="${2:-}" ;;
        action)
            [[ $# -le 5 ]] || { echo 'Expected action project namespace environment dry_run' >&2; return 2; }
            action="${1:-deploy}"; positional_namespace="${3:-}" ;;
        *) echo 'Unknown Secret contract' >&2; return 2 ;;
    esac
    case "$action" in
        help|-h|--help)
            echo 'Pull Secret: deploy/status/uninstall; preserve the component positional API.'
            echo 'Execution needs explicit CLUSTER, KUBECONFIG, SUNMOON_KUBECTL and SUNMOON_EXPECTED_CLUSTER_UID.'
            return 0 ;;
        deploy|status|uninstall) ;;
        *) echo 'Unsupported pull-secret action; no credential YAML is generated by deployment entries.' >&2; return 2 ;;
    esac
    [[ "${CLUSTER:-}" =~ ^(KIND|C[1-9][0-9]*)$ ]] || {
        echo 'Explicit CLUSTER required; no default cluster fallback' >&2; return 1;
    }
    [[ -f "$config" && ! -L "$config" ]] || { echo 'Component Secret configuration missing' >&2; return 1; }
    # Existing trusted .conf still owns Secret name/namespace/restart preferences.
    # DOCKER_* fields are historical and are never used for authentication here.
    source "$config" >/dev/null 2>&1 || { echo 'Component Secret configuration failed' >&2; return 1; }
    source "$root/utils/cluster-config-mapping.sh"
    apply_cluster_config_mapping
    namespace="${positional_namespace:-${NAMESPACE:-${SECRET_NAMESPACE:-$default_namespace}}}"
    [[ "${SECRET_TYPE:-kubernetes.io/dockerconfigjson}" == kubernetes.io/dockerconfigjson ]] || {
        echo 'Registry Secret type must be kubernetes.io/dockerconfigjson' >&2; return 1;
    }
    source "$root/utils/deploy-target.sh"
    sunmoon_deploy_target_init "$root" || return 1
    if [[ "$action" == deploy ]]; then
        source "$root/sunmoonai/registry-platform/lib/config.sh"
        registry_load_config || return 1
        [[ -n "${REGISTRY_CREDENTIALS_FILE:-}" ]] || { echo 'Private registry credentials file required' >&2; return 1; }
    fi
    local -a restart_args=()
    local component
    if [[ "$action" == deploy && "${RESTART_COMPONENTS:-false}" == true ]]; then
        local -a components=()
        IFS=',' read -r -a components <<< "${RESTART_COMPONENTS_LIST:-}"
        for component in "${components[@]}"; do
            # Trim whitespace without evaluating configured text as commands.
            component="${component#"${component%%[![:space:]]*}"}"
            component="${component%"${component##*[![:space:]]}"}"
            [[ -z "$component" ]] || restart_args+=(--restart "$component")
        done
    fi
    sunmoon_deploy_target_check "$root" || return 1
    python3 -B "$root/sunmoonai/registry-platform/pull_secret.py" "$action" \
        --namespace "$namespace" --name "${SECRET_NAME:-harbor-registry-secret}" \
        "${restart_args[@]}" --apply
)
