apiVersion: v1
kind: Secret
metadata:
    name: valkey-auth
    namespace: data-platform-dev
stringData:
    probe-password: ENC[AES256_GCM,data:RgAdYQw69pKyxyLToXBIZ7HjK7amGsK94/Cik/pFPKGxtrp97kNmeA==,iv:qc6bePPSv3uWPZx0irUk1XTGJLc7OGSD3ovbNWcXkbA=,tag:w3xL/Pdx3SVhfhGRh7QGVw==,type:str]
    users.acl: ENC[AES256_GCM,data:eG54dq0Bglr1lVRZQSHVluAOWDbuhVj1DQAqFhzlQ7/EDvTP0zPUICXmmbITe7xrGKKGlQytBbmcIfZBzAzNhzBvA9l9BYvC4JewYREODyS+dhGate2GSOMjU6gNNBPX8qGljDo4Ql+ZbRQgtvytayx8g6pPVLlm1RgH1qeJYPmwyWSNjzUYysQxlzNo4KUbsxAlFB2MpjB7N8/Adga0G9BN1W538wMc4yaLenp8RSIQuIh0S6GOpM31V6NIVM/BBO3H1VpIc4PAvILEgbjOBJImpwejg2vxgZCfuc+7s4xN4dZWNgsoJFXK8Va0Jm5yfrnhiFqg76fxoYi961jbQQRegRQUia19yKCEwpGQk3TojDkQ7R6vuwqLd7RJoHPMGyGoIt8rMSZpaeDcudIBBoD2WL7+KZ+Xi0wWo2CbGDKWSpnthFWtATOgRFB1,iv:UuGzYzCHZ7cBTj+IBj1PguvndY5XzJd9HtwRYhfzsqE=,tag:VF9+1Rb1XbaBZal3vgrHjw==,type:str]
    valkey.conf: ENC[AES256_GCM,data:jGk3SXf2jMX3VErJe/CP2oEPJvHlTFMb2cl4H4TYCgcyZTKcXBgW8lO7gm7QvAarWbiapvfx+U/zt9/DTUya9QDCMFbZt9kuGF7Di/cEF+LetUkVXPTI+VvTH277vG9MPqzZHX2warCfIJIK+LZ8sLIwLtEokc/IrG21gY8vHFFNlZ/Gs6ZgmDGzQ6qyV8m/zYdOfNzKRKLq7FdlqA6IET8=,iv:JrtRPnp3LDP44gXgJ09NJWtSulVoVeyuv5nzkqYPXd0=,tag:acN6VO0QmM+pVU1pOEnMJw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0MUdpbjJHWHAwdktNTDZo
            dWNRTEplbXArVjBObEhhc0h5UEN3ZzluQ0FNClcyR0ZwN09oWDdaNm9Ma0dMakpD
            U2RGaHQ3a3IrWXI0Zm5MVU5wMTZ4dVEKLS0tIFFBOGxLVEkwa3gwWjk2cXlCSDUv
            VHdaenRkWjR1NzFQeUlwL0p6TkQ0eFEKtYIfQWyAuoPUO+cV7vYsXosI8LiXU/Za
            g9h+d9aakpYDk4LBbLkAZQbLWAysEsQniBRKP5DNybFlN2uPH6h5pg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1usl2cz5ltxz7au5tdpjqz7t77nzh3a29dgyewwfexqcctjfp2edq5yy6ge
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-04T07:27:29Z"
    mac: ENC[AES256_GCM,data:G+3C1RgKOxTiDqlygeCDFKnghAObDV/xZXHktXI45FlUNm8b9bMyQ1rJ6XIvLP+texLjc1No7rWNUjvUStv0tnnGSq3N6KsfG/MsMvxfrFnejh0sd89jPDvPSFKhAo/nrwRA3fLxB0+Y/O0vbN3ihfI5ZodHtHjfd1kLS2Dwpfw=,iv:GVLOJGpuzKcw4wD991q+cPM0stxQK+uBSiQovg2gE+0=,tag:ycByDawsSBec1/gSnadnvw==,type:str]
    version: 3.13.3
