apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ${PVC_NAME}
  namespace: ${NAMESPACE}
  labels:
    app: document-converter
spec:
  accessModes:
    - ${PVC_ACCESS_MODE}
  storageClassName: ${PVC_STORAGE_CLASS}
  resources:
    requests:
      storage: ${PVC_STORAGE_SIZE}

