apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: kibana-stripprefix
  namespace: data-platform-dev
  labels:
    app: data-platform-ingress
    component: kibana-stripprefix
    project: sunmoonai
spec:
  stripPrefix:
    prefixes:
      - "/kibana"

