apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: llmops-app-ssr-ingress
  namespace: {{NAMESPACE}}
  labels:
    app: app-platform-ingress
    component: llmops-app-ssr
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`{{NODE_IP}}`) && PathPrefix(`/`)
      kind: Rule
      services:
        - name: {{SERVICE_NAME}}
          port: {{SERVICE_PORT}}
    - match: Host(`{{UNIFIED_HOST}}`) && PathPrefix(`/`)
      kind: Rule
      services:
        - name: {{SERVICE_NAME}}
          port: {{SERVICE_PORT}}
