apiVersion: v1
kind: Secret
metadata:
    name: tpl-browser-secrets
    namespace: app-platform-dev
stringData:
    WEB_CASDOOR_CLIENT_SECRET: ENC[AES256_GCM,data:IrdDlZuRf+izUr2sIc47GwyurF9rQAi/uYyTnfVYtk7ylObREpzJrQ==,iv:1OQ9CLdn0ePmWV5ReWRcBUbWEdAcKrPJLtq8sj2BbWo=,tag:Sjm7/fG3IDqLX1J1UqOlPQ==,type:str]
    ADMIN_CASDOOR_CLIENT_SECRET: ENC[AES256_GCM,data:XYNdX+pAvnL4GNwZHWRY6YE9OpxKU0aC+Dk2CrHxH8eBhhkN3528Jw==,iv:r0G/2Ps1Lb9VBUVZ1ljdHplHHdVev/6OfVnuQqCTdIM=,tag:yQfnp0EJN3Bqp8qfTm2lkg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvdHVJcGNvMWcrdjM3MmRI
            Q1FxblR5Y0pQSmpKcUVxZnFYbVovckxhbjNJCnhhcnhrK0VCdXlhd1ZzN09HRi83
            VW9oV2IreERJOVlXNWdQa3N1S0tpTk0KLS0tIHJscllrdXViNlVqOVp5SnN3R3BL
            R1orT3p5UXZGN1VZNmFHOWRvalFvdEEKlLjYq86RVpbx1iPuvkYKEF2Ijfevfrl0
            WGY+wdztZSqZ2pI5U8jvLYDJrqEPo2aezQi3KojQWg0eehPfpiBMxg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1usl2cz5ltxz7au5tdpjqz7t77nzh3a29dgyewwfexqcctjfp2edq5yy6ge
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-06T07:22:26Z"
    mac: ENC[AES256_GCM,data:UEbJeIutM9Wck73iN851ZXbkh4Kg8Cu3ofBWX1u0EY+WJ9V/dgcRX90E9VennPzFs9UgHt0tTNekPSWHeha3zoUeuev8AJBiNnWRluA+px+LRUC/xj043YqEBzLi7Jd8UAvDaI0MBxGxFxXwEc2DMlkbzq7Ok0aSy7PU/8Rkchs=,iv:06w5VTHSfeDnltHAwafZ7OxLIQYr+J/ReuJ1ZN+bQtw=,tag:RK9QWvg3xEfpKleLqe+p5Q==,type:str]
    version: 3.13.3
