apiVersion: v1
kind: Secret
metadata:
  name: celeryworker-info-admin-backend-secret
  namespace: app-platform-dev
  labels:
    app: celeryworker-info-admin-backend
    component: celery-worker
    backend: info-admin-backend
type: Opaque
stringData:
  CELERY_BROKER_URL: "amqp://info-admin-backend-worker:info-admin-backend-worker-dev@rabbitmq-sunmoonai.messaging-platform-dev.svc.cluster.local:5672/info-development"
  CELERY_RESULT_BACKEND: ""
