apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: jenkins-policy-headers
  namespace: cicd-platform-dev
  labels:
    app: cicd-platform-ingress
    component: jenkins-policy-headers
    project: sunmoonai
spec:
  headers:
    customRequestHeaders:
      X-Jenkins-Version: "2.426"
      X-Forwarded-Prefix: "/jenkins"  # 告诉 Jenkins 原始请求的路径前缀
    customResponseHeaders:
      X-Jenkins-Status: "active"

