apiVersion: v1
kind: PersistentVolume
metadata:
  name: pgadmin-sunmoonai-dev-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /data/kind-local-storage/pgadmin
    type: DirectoryOrCreate
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values: [kind-worker]
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pgadmin-sunmoonai-dev-pvc
  namespace: ops-platform-dev
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: ""
  volumeName: pgadmin-sunmoonai-dev-pv
