{{- $watchedNamespaces := include "aistor.watchedNamespaces" (dict "operator" "object-store" "root" $.Values) | fromJsonArray }}
{{- if and (include "aistor.operatorEnabled" (dict "operator" "object-store" "root" $.Values)) $watchedNamespaces }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: aistor:object-store-cluster
  annotations:
    aistor.min.io/authors: MinIO, Inc.
    aistor.min.io/license: Enterprise
    aistor.min.io/support: https://subnet.min.io
    aistor.min.io/version: RELEASE.2026-06-10T05-02-21Z
    {{- if $.Values.annotations }}
    {{ $.Values.annotations | toYaml | nindent 4 }}
    {{- end }}
  {{- if $.Values.labels }}
  labels:
    {{ $.Values.labels | toYaml | nindent 4 }}
  {{- end }}
rules:
  - apiGroups: ["apiextensions.k8s.io"]
    resources: ["customresourcedefinitions"]
    verbs: ["get"]

  - apiGroups: [""]
    resources: ["nodes"]
    verbs: ["get"]

{{- if eq (include "aistor.tokenValidation" $) "TokenReview" }}
  - apiGroups: ["rbac.authorization.k8s.io"]
    resources: ["clusterrolebindings"]
    verbs: ["create", "delete", "get", "update"]

  - apiGroups: ["rbac.authorization.k8s.io"]
    resources: ["clusterroles"]
    resourceNames: ["aistor:tokenreview"]
    verbs: ["bind"]
{{- end }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: aistor:object-store-cluster
  annotations:
    aistor.min.io/authors: MinIO, Inc.
    aistor.min.io/license: Enterprise
    aistor.min.io/support: https://subnet.min.io
    aistor.min.io/version: RELEASE.2026-06-10T05-02-21Z
    {{- if $.Values.annotations }}
    {{ $.Values.annotations | toYaml | nindent 4 }}
    {{- end }}
  {{- if $.Values.labels }}
  labels:
    {{ $.Values.labels | toYaml | nindent 4 }}
  {{- end }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: aistor:object-store-cluster
subjects:
  - kind: ServiceAccount
    name: object-store
    namespace: {{ include "aistor.namespace" $ }}
{{- end }}
