{{- if (include "aistor.operatorEnabled" (dict "operator" "warp" "root" $.Values)) }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: aistor:warp
  annotations:
    aistor.min.io/authors: MinIO, Inc.
    aistor.min.io/license: Enterprise
    aistor.min.io/support: https://subnet.min.io
    aistor.min.io/version: RELEASE.2026-06-10T05-02-21Z
    {{- if $.Values.annotations }}
    {{ $.Values.annotations | toYaml | nindent 4 }}
    {{- end }}
  {{- if $.Values.labels }}
  labels:
    {{ $.Values.labels | toYaml | nindent 4 }}
  {{- end }}
rules:
  ### Standard operator permissions
  
  # Allow the operator to manage events for logging and debugging
  - apiGroups: [""]
    resources: ["events"]
    verbs: ["create", "patch"]


  ### Operator permissions for managing Warp components

  # Monitor Warp resources
  - apiGroups: ["aistor.min.io"]
    resources: ["warps"]
    verbs: ["get", "list", "watch"]

  # Allow updating the status of Warp resources
  - apiGroups: ["aistor.min.io"]
    resources: ["warps/status"]
    verbs: ["update"]

  # Allow updating finalizers (required by blockOwnerDeletion in owner references)
  - apiGroups: ["aistor.min.io"]
    resources: ["warps/finalizers"]
    verbs: ["update"]

  # Monitor configuration maps
  - apiGroups: [""]
    resources: ["configmaps"]
    verbs: ["get", "list", "watch"]

  # Manage secrets
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["create", "delete", "get", "list", "update", "watch"]

  # Manage batch jobs
  - apiGroups: ["batch"]
    resources: ["jobs"]
    verbs: ["create", "list", "watch"]

  # Manage statefulsets
  - apiGroups: ["apps"]
    resources: ["statefulsets"]
    verbs: ["create", "list", "update", "watch"]

  # Manage services
  - apiGroups: [""]
    resources: ["services"]
    verbs: ["create", "list", "update", "watch"]

  # Manage pods (delete required for RestartPodsIfNotRunning)
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["delete", "list", "watch"]

  # Monitor ObjectStore resources
  - apiGroups: ["aistor.min.io"]
    resources: ["objectstores"]
    verbs: ["get", "list", "watch"]


  ### Service account, RBAC and MinIO policy management

  # Service accounts
  - apiGroups: [""]
    resources: ["serviceaccounts"]
    verbs: ["create", "list", "update", "watch"]

  # MinIO policy bindings
  - apiGroups: ["sts.min.io"]
    resources: ["policybindings"]
    verbs: ["create", "delete", "list", "update", "watch"]
{{- end }}
