{{- if not (include "aistor.isOpenShift" $) }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: aistor:certificate-management
  annotations:
    aistor.min.io/authors: MinIO, Inc.
    aistor.min.io/license: Enterprise
    aistor.min.io/support: https://subnet.min.io
    aistor.min.io/version: RELEASE.2026-06-10T05-02-21Z
    {{- if $.Values.annotations }}
    {{ $.Values.annotations | toYaml | nindent 4 }}
    {{- end }}
  {{- if $.Values.labels }}
  labels:
    {{ $.Values.labels | toYaml | nindent 4 }}
  {{- end }}
rules:
  # Core CSR operations
  - apiGroups: ["certificates.k8s.io"]
    resources: ["certificatesigningrequests"]
    verbs: ["create", "delete", "get", "list", "watch"]

  # Required to actually approve/deny via the subresource
  - apiGroups: ["certificates.k8s.io"]
    resources: ["certificatesigningrequests/approval"]
    verbs: ["get", "update"]

  # To read back the signed certificate
  - apiGroups: ["certificates.k8s.io"]
    resources: ["certificatesigningrequests/status"]
    verbs: ["get"]

  # Needed to allow approval for specific signers
  - apiGroups: ["certificates.k8s.io"]
    resources: ["signers"]
    # We can't scope, because `MINIO_OPERATOR_CSR_SIGNER_NAME` may be set to a custom signer
#   resourceNames:
#     - kubernetes.io/kubelet-serving       # Required for vanilla Kubernetes
#     - beta.eks.amazonaws.com/app-serving  # Required on EKS
    verbs: ["approve"]

  # Monitoring nodes is required to detect if nodes are running inside EKS
  # (EKS requires custom certificate handling)
  - apiGroups: [""]
    resources: ["nodes"]
    verbs: ["list"]
{{- end }}
