{{- if include "aistor.webhookEnabled" . }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: aistor:object-store-webhook-cluster
  annotations:
    aistor.min.io/authors: MinIO, Inc.
    aistor.min.io/license: Enterprise
    aistor.min.io/support: https://subnet.min.io
    aistor.min.io/version: RELEASE.2026-06-10T05-02-21Z
    {{- if $.Values.annotations }}
    {{ $.Values.annotations | toYaml | nindent 4 }}
    {{- end }}
  {{- if $.Values.labels }}
  labels:
    {{ $.Values.labels | toYaml | nindent 4 }}
  {{- end }}
rules:
  {{- if not (include "aistor.isOpenShift" $) }}
  # Allow updating the webhook configuration (not for OpenShift)
  - apiGroups: ["admissionregistration.k8s.io"]
    resources: ["mutatingwebhookconfigurations"]
    verbs: ["get", "update"]
  {{- end }}

  # List nodes (required for making scheduling decisions)
  - apiGroups: [""]
    resources: ["nodes"]
    verbs: ["list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: aistor:object-store-webhook-cluster
  annotations:
    aistor.min.io/authors: MinIO, Inc.
    aistor.min.io/license: Enterprise
    aistor.min.io/support: https://subnet.min.io
    aistor.min.io/version: RELEASE.2026-06-10T05-02-21Z
    {{- if $.Values.annotations }}
    {{ $.Values.annotations | toYaml | nindent 4 }}
    {{- end }}
  {{- if $.Values.labels }}
  labels:
    {{ $.Values.labels | toYaml | nindent 4 }}
  {{- end }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: aistor:object-store-webhook-cluster
subjects:
  - kind: ServiceAccount
    name: object-store-webhook
    namespace: {{ include "aistor.namespace" $ }}
{{- end }}
