{{- range $op, $int := include "aistor.operators" . | fromYaml }}
{{- $emptyObj := "{}" | fromJson -}}
{{- $operators := $.Values.operators | default $emptyObj -}}
{{- $opValue := index $operators $op | default $emptyObj }}
{{- $watchedNamespaces := include "aistor.watchedNamespaces" (dict "operator" $op "root" $.Values) | fromJsonArray }}
{{- if not $opValue.disabled }}
{{- range $ns := $watchedNamespaces }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ $op }}
  namespace: {{ $ns }}
  annotations:
    aistor.min.io/authors: MinIO, Inc.
    aistor.min.io/license: Enterprise
    aistor.min.io/support: https://subnet.min.io
    aistor.min.io/version: RELEASE.2026-06-10T05-02-21Z
    {{- if $.Values.annotations }}
    {{ $.Values.annotations | toYaml | nindent 4 }}
    {{- end }}
  {{- if $.Values.labels }}
  labels:
    {{ $.Values.labels | toYaml | nindent 4 }}
  {{- end }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: aistor:{{ $op }}
subjects:
  - kind: ServiceAccount
    name: {{ $op }}
    namespace: {{ include "aistor.namespace" $ }}
{{- end }}
{{- end }}
{{- end }}
