{{- if include "aistor.webhookEnabled" . }}
---
apiVersion: v1
kind: ServiceAccount
automountServiceAccountToken: false
metadata:
  name: object-store-webhook
  namespace: {{ include "aistor.namespace" $ }}
  annotations:
    aistor.min.io/authors: MinIO, Inc.
    aistor.min.io/license: Enterprise
    aistor.min.io/support: https://subnet.min.io
    aistor.min.io/version: RELEASE.2026-06-10T05-02-21Z
    {{- if $.Values.annotations }}
    {{ $.Values.annotations | toYaml | nindent 4 }}
    {{- end }}
  {{- if $.Values.labels }}
  labels:
    {{ $.Values.labels | toYaml | nindent 4 }}
  {{- end }}
{{- end -}}
