{{- $emptyObj := "{}" | fromJson }}
{{- $operators := .Values.operators | default $emptyObj }}
{{- $objectStore := index $operators "object-store" | default $emptyObj }}
{{- if not $objectStore.disabled }}
apiVersion: v1
kind: Service
metadata:
  name: object-store-operator
  namespace: {{ include "aistor.namespace" $ }}
  annotations:
    aistor.min.io/authors: MinIO, Inc.
    aistor.min.io/license: Enterprise
    aistor.min.io/support: https://subnet.min.io
    aistor.min.io/version: RELEASE.2026-06-10T05-02-21Z
    {{- if include "aistor.isOpenShift" $ }}
    service.beta.openshift.io/serving-cert-secret-name: object-store-operator-tls
    {{- end }}
    {{- if $.Values.annotations }}
    {{ $.Values.annotations | toYaml | nindent 4 }}
    {{- end }}
  {{- if $.Values.labels }}
  labels:
    {{ $.Values.labels | toYaml | nindent 4 }}
  {{- end }}
spec:
  type: ClusterIP
  ports:
    - port: 4221
      name: http
  selector:
    aistor.min.io/name: object-store-operator
    operator: leader
    {{- if $.Values.labels }}
    {{ $.Values.labels | toYaml | nindent 4 }}
    {{- end }}
{{- end }}
