apiVersion: v1
kind: Secret
metadata:
  name: harbor-registry-secret
  namespace: app-platform-dev
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: eyJhdXRocyI6eyJoYXJib3Iuc3VubW9vbmFpLmNvbSI6eyJ1c2VybmFtZSI6ImFkbWluIiwicGFzc3dvcmQiOiJIYSFyMTM1OWFkbWluIiwiYXV0aCI6IllXUnRhVzQ2U0dFaGNqRXpOVGxoWkcxcGJnPT0ifX19
