apiVersion: v1
kind: Secret
metadata:
  name: nodebullworker-research-web-backend-secret
  namespace: app-platform-dev
  labels:
    app: nodebullworker-research-web-backend
    component: node-bull-worker
    backend: research-web-backend
type: Opaque
stringData: {}
