apiVersion: v1
kind: Secret
metadata:
    name: rabbitmq-auth
    namespace: messaging-platform-dev
stringData:
    erlang-cookie: ENC[AES256_GCM,data:zLjY4p2uuGvQGFQB2zUO0AlSK6CD/A==,iv:e4Cvnbfs3VILJSBOWCRvchTORUNEOSm/1C21Q/bULBg=,tag:oM0kFLXORLQeNbOvrQ9O/w==,type:str]
    username: ENC[AES256_GCM,data:V+uuDEo=,iv:TYugwQh5Du1yDV3qU7d5kLcA2pHZLY4syg0feGM2Tg4=,tag:XVWIKxWNSQtfU9H/dqKOgw==,type:str]
    password: ENC[AES256_GCM,data:jAxXtIPMXd5/U5YmJg==,iv:8tkd8OPmniQ4xMXibIu9CpDjJphaaerlrP/JNbNKn1o=,tag:uXPNLe3nZSqY7VBSR0+huw==,type:str]
    rabbitmq.conf: ENC[AES256_GCM,data:dY8i98rIBTAQ32uNaNWj1DhEI/HtzZyvhJKAZJGzSF535qZt133ODnYGH7dEzgrCkxKpXY3VMG0Lg/fu4tU5XTonejtqW6zIqnxDjvBEHA4FVBXdAkw1g6GO1ew0wW+Ga/raBXXzQAmb82RDgux4gM1AD3gFnehojWYEMxDxORmuGPYWi5Z6etBpLUnSinh3zWBLlZwo56ecMDuAI1fmHw==,iv:3Nu877HnQqpesqWx0u1vWS2UK0oSuHXSoROj37NU76Y=,tag:ZtifxiWOjOZS8qjzjKBiSA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxVkZsOGlJYzRZQlRZRTRh
            MzlUd2tDK3h0OEw5dkNLZDh4MnNncGRQdTFvCnV5V2UweHYyZHZzNmlFdFBvaDdy
            RmN5Uno5UmtuSjZCekd1N3RzZlZwaEUKLS0tIERvRzhDVCtWbzJUMVRKUDRsS29I
            YWFOa2dCNHN6Y1VQSDg2NVlQTUZ1MWsKwBnzchgkProp48jkh7zeayteqpVa9cao
            qXRVVfwi0Q0JTNXKA+PsM8m3fpQOMWyGjKG3BCsSJxDk6h1wM5XZuQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1usl2cz5ltxz7au5tdpjqz7t77nzh3a29dgyewwfexqcctjfp2edq5yy6ge
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-03T04:10:51Z"
    mac: ENC[AES256_GCM,data:8JdG28iX9KK7Sg2u1mML1e8oqkiaG/YiCz7T4DEsA6pylsPSZ8yiYBrPP7F7YpFEUi9KsFngyxKAfolKUAedaS72gNbmW/Ba9qaEprdjF6Y7z505OV+Mc7ppozpBCr/mMwDvJEwzRkMfGiHpdWMLeSfrjwYXIC7D2KTmQGhhYIQ=,iv:wRFGvPFRPd+RhsTlFQuBTj+3U+fUstFuchnNfmoGPuU=,tag:kpn7qiSprEu0uLBG8Bk+/w==,type:str]
    version: 3.13.3
