apiVersion: v1
kind: PersistentVolume
metadata:
  name: sunmoon-kind-rabbitmq
  annotations:
    sunmoonai.com/storage-owner: sunmoon-kind
    kustomize.toolkit.fluxcd.io/prune: disabled
spec:
  capacity: {storage: 4Gi}
  accessModes: [ReadWriteOnce]
  volumeMode: Filesystem
  persistentVolumeReclaimPolicy: Retain
  storageClassName: sunmoon-static
  local:
    path: /data/kind-local-storage/rabbitmq
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values: [sunmoon-kind-worker2]
  claimRef:
    namespace: messaging-platform-dev
    name: rabbitmq-data
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rabbitmq-data
  namespace: messaging-platform-dev
  annotations:
    kustomize.toolkit.fluxcd.io/prune: disabled
spec:
  accessModes: [ReadWriteOnce]
  storageClassName: sunmoon-static
  volumeName: sunmoon-kind-rabbitmq
  resources:
    requests: {storage: 4Gi}
