apiVersion: v1
kind: Secret
metadata:
  name: harbor-secret
  namespace: cicd-platform-dev
type: Opaque
data:
  HARBOR_ADMIN_PASSWORD: SGFyYm9yQDEyMzQ1
  HARBOR_ADMIN_USERNAME: YWRtaW4=
  RESTART_COMPONENTS_LIST: aGFyYm9yLWNvcmUsaGFyYm9yLWpvYnNlcnZpY2UsaGFyYm9yLXBvcnRhbA==
  RESTART_PRIORITY: NTA=
