apiVersion: v1
kind: ConfigMap
metadata:
  name: ${LLMOPS_SERVICE_CONFIGMAP_NAME}
  namespace: ${NAMESPACE}
  labels:
    app: llmops-service
    component: configmap
    environment: ${ENVIRONMENT}
    managed-by: deploy-script
data:
  PROJECT_NAME: "${PROJECT_NAME}"
  SERVER_NAME: "${SERVER_NAME}"
  SERVER_HOST: "${SERVER_HOST}"
  SERVER_BOT: "${SERVER_BOT}"
  BACKEND_CORS_ORIGINS: "${BACKEND_CORS_ORIGINS}"
  POSTGRES_SERVER: "${POSTGRES_SERVER}"
  POSTGRES_PORT: "${POSTGRES_PORT}"
  POSTGRES_USER: "${POSTGRES_USER}"
  POSTGRES_DB: "${POSTGRES_DB}"
  NEO4J_SERVER: "${NEO4J_SERVER}"
  NEO4J_PORT: "${NEO4J_PORT}"
  NEO4J_USERNAME: "${NEO4J_USERNAME}"
  NEO4J_AUTH: "${NEO4J_AUTH}"
  NEO4J_BOLT: "${NEO4J_BOLT}"
  USERS_OPEN_REGISTRATION: "${USERS_OPEN_REGISTRATION}"
  NEO4J_FORCE_TIMEZONE: "${NEO4J_FORCE_TIMEZONE}"
  NEO4J_AUTO_INSTALL_LABELS: "${NEO4J_AUTO_INSTALL_LABELS}"
  NEO4J_MAX_CONNECTION_POOL_SIZE: "${NEO4J_MAX_CONNECTION_POOL_SIZE}"
  MULTI_MAX: "${MULTI_MAX}"
  EMAIL_RESET_TOKEN_EXPIRE_HOURS: "${EMAIL_RESET_TOKEN_EXPIRE_HOURS}"
  EMAIL_TEMPLATES_DIR: "${EMAIL_TEMPLATES_DIR}"
  EMAIL_TEST_USER: "${EMAIL_TEST_USER}"
