{{- $secretConfigName := include "aistor.configSecretName" .Values }}

{{- if and $secretConfigName (not (.Values.secrets).existingSecret) }}

{{- if not .Values.secrets.accessKey }}
{{- fail ".secrets.accessKey is required" }}
{{- end }}
{{- if not .Values.secrets.secretKey }}
{{- fail ".secrets.secretKey is required" }}
{{- end }}

apiVersion: v1
kind: Secret
metadata:
  name: {{ $secretConfigName | quote }}
  namespace: {{ $.Values.namespaceOverride | default $.Release.Namespace | quote }}
  {{- if $.Values.annotations }}
  annotations:
    {{ $.Values.annotations | toYaml | nindent 4 }}
  {{- end }}
  {{- if $.Values.labels }}
  labels:
    {{ $.Values.labels | toYaml | nindent 4 }}
  {{- end }}
type: Opaque
data:
  {{- $config := "" }}
  {{- $config = printf "%sexport MINIO_ROOT_USER=%s\n" $config (.Values.secrets.accessKey | quote) }}
  {{- $config = printf "%sexport MINIO_ROOT_PASSWORD=%s\n" $config (.Values.secrets.secretKey | quote) }}
  {{- if .Values.secrets.disableRoot }}
  {{- $config = printf "%sexport MINIO_API_ROOT_ACCESS=\"off\"\n" $config }}
  {{- end }}
  config.env: {{ $config | b64enc | quote }}
{{- end }}
