apiVersion: v1
kind: Secret
metadata:
  name: redis-llmopsservice-secret
  namespace: data-platform-dev
type: Opaque
data:
  REDIS_DB: MQ==
  REDIS_HOST: cmVkaXMtc3VubW9vbmFpLmRhdGEtcGxhdGZvcm0tZGV2LnN2Yy5jbHVzdGVyLmxvY2Fs
  REDIS_PASSWORD: U3Ryb25nUmVkaXNQYXNzdzByZCE=
  REDIS_PORT: NjM3OQ==
  REDIS_SSL: ZmFsc2U=
