apiVersion: v1
kind: Secret
metadata:
    name: tpl-redis-provision
    namespace: data-platform-dev
stringData:
    password: ENC[AES256_GCM,data:5T2vG0xYwZ50vbf44+afqlEfHwxLwR/giTjREQE7MQed+UvjlG/Z5g==,iv:UrkKZMCVAAGdKvhmMTO4qU5WEf/ei6VNb1G/jPA7qNA=,tag:e6u3n/ux6AKoGeLZQ8aUGw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGTDNyM1d4VU1MS0JHR2FK
            U0xnNUpJb0J1VmtlMEEyUUIzYXd0UmprdUdRCmpuT3dGTHZjTFB2eHYrSVlkNFN1
            cHNIRkYyZEpiUTNyay80RTEzQUdtaDgKLS0tIG9oZjhoM1RWajFFSGJKWEhrWGRx
            K0RDVWZrdmFiMFRXN2FGTWJtc09wVjAKbXkEs4VbjOfd4jKwB6tz77eqYTQiTH/i
            tq2iCEMVgMs0TQFbaLmnr3E20ERk0F2AkChSL5PJzfjB43FYx96Q3w==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1usl2cz5ltxz7au5tdpjqz7t77nzh3a29dgyewwfexqcctjfp2edq5yy6ge
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-06T07:22:19Z"
    mac: ENC[AES256_GCM,data:0xdK5alcEsTyL4+8K8dCVwixDZ29jtDmJbVyjpBj8TDlz7pVW1nlX9aHG8ldPJbqpp82EoyoW15cnM/WXvHEVe/ElSHs4SSbd+sDeF8gFtT/VLrP7HMhkDYMszjqNTBJEg+XT8iYC12uXT5T9cEbFoEWiKsXD9ql+THhOUwwp/0=,iv:CVPgrOXr0eRwbu3kvLtdoBRgnSSrjkJxYyuHEsTJTPE=,tag:3InB4oCsHzSxunqF3/Fm5Q==,type:str]
    version: 3.13.3
