apiVersion: v1
kind: Secret
metadata:
    name: tpl-redis-runtime
    namespace: app-platform-dev
stringData:
    REDIS_USER: ENC[AES256_GCM,data:79U1//UeBVJh1k8=,iv:nNE85F5pZDME5rQfWCs9rp0gQZKIEduTOApx/Xbrlnc=,tag:+gzgUJxEOeK+lhw8z64vtQ==,type:str]
    REDIS_PASSWORD: ENC[AES256_GCM,data:8Plg5bGnC9FNb8yhxJnkkel9XSLBGL6ttuNDe43vLU5MK3nBXKkLXg==,iv:rKcmIW7oksDPSo/BTkxL+lUDkYPaPjv4ygcNJl+UINM=,tag:xVzKQUuhsR+xy8PEki8c9Q==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpZGltV243V2pLalFSTFVO
            RFQyek1Oelp3VVVQelhUL1gwTi9zK0lZWkRrCnFmU2VMQjlVeVhyV1pFN2FtaEtY
            UWVVaE0wUVNYUEEwZE9uRGMzQUtBSFkKLS0tIHM2NnlWeTlwczlBckV3QTk1R21T
            SEdnY1kxUWRMZ0o0VWEvckUwNUNDK1UKbw8Yu389tqwOX088XjcjVrMau4wGFkRv
            bdbcRsRBTTcZnUeBIsa5I193zL4SsTN+RlahJ03aVdtz0zUqO2EXYg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1usl2cz5ltxz7au5tdpjqz7t77nzh3a29dgyewwfexqcctjfp2edq5yy6ge
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-06T07:22:21Z"
    mac: ENC[AES256_GCM,data:hExorQ5sG/oYmARbK7/i46N1JKCx/sSU56Hkt9q79ib5FXVL473exfSC6VptuEC/99RASIvr2M1CNXplCEBOwA1bpyNdfinJ61bM+aTmAQHc2P3roM8blMWf+0tqB1kuhOrwwLdoy5Fzm04eFjx58N8Xgg9xvxbSGi3sfoh99dI=,iv:qqHXg+046GAl0yaZJkxymwPbha8sp/UUKhi97ijfaMc=,tag:PKaSiJzwhuI3eBXyY+w/DA==,type:str]
    version: 3.13.3
