apiVersion: v1
kind: ConfigMap
metadata:
  name: llmops-app-ssr-config
  namespace: ${NAMESPACE}
  labels:
    app: llmops-app-ssr
data:
  SERVER_NAME: "llmops-ssr.sunmoonai.com"
  SERVER_HOST: "https://llmops-ssr.sunmoonai.com"
  NODE_ENV: "production"
  APP_ENV: "production"
  NITRO_HOST: "0.0.0.0"
  NITRO_PORT: "3000"
  NUXT_TELEMETRY_DISABLED: "1"
  BACKEND_API_URL: "http://backend-bff.app-platform-dev"  # 按实际后端修改
