apiVersion: v1
kind: Secret
metadata:
  name: postgresql-authservice-db-secret
  namespace: data-platform-dev
type: Opaque
data:
  DB_HOST: cG9zdGdyZXNxbC1zdW5tb29uYWkuZGF0YS1wbGF0Zm9ybS1kZXYuc3ZjLmNsdXN0ZXIubG9jYWw=
  DB_NAME: YXV0aF9kYg==
  DB_PASSWORD: enltMTIz
  DB_PORT: NTQzMg==
  DB_SSLMODE: ZGlzYWJsZQ==
  DB_USER: c3VubW9vbmFpX2Rldg==
