apiVersion: v1
kind: Secret
metadata:
  name: info-admin-backend-secret
  namespace: ${NAMESPACE}
  labels:
    app: info-admin-backend
type: Opaque
stringData:
  KNOWLEDGE_APP_API_KEY: "${KNOWLEDGE_APP_API_KEY}"
