apiVersion: v1
kind: Secret
metadata:
  name: mongo-express-secrets
  namespace: ops-platform-dev
type: Opaque
data:
  basic-auth-password: YlVJR25ZUUszUktkZG9QUA==
  mongo-express-admin-user: YWRtaW4=
  mongo-express-password: TW5JdXRucWxaQXZ2anBG
  mongodb-auth-password: enltMTIz
  site-cookie-secret: SHFOdENpZ0huNXQ0amtVeDQ0OE9XOWI4bGZoNmI=
  site-session-secret: TzFqZmMwclh0bm1USnNrajdhWUtFa0h4dVlHZktDdA==
