apiVersion: v1
kind: Secret
metadata:
  name: mongo-express-secrets
  namespace: ops-platform-dev
type: Opaque
data:
  basic-auth-password: TkV1Z3BGSTY5Sm1Tc0Q5RQ==
  mongo-express-admin-user: YWRtaW4=
  mongo-express-password: Z1dEZ0k0Y1FmZzNSSVBmQw==
  mongodb-auth-password: enltMTIz
  site-cookie-secret: UloyWGhEaHluY2Vidk5hQ0RNRFVWUDFSM1kxTTlU
  site-session-secret: WERDYXhJdEFBTlZNYU5LQmdScWNaa3JOZnNGeWJs
