apiVersion: v1
kind: Secret
metadata:
  name: mongo-express-secrets
  namespace: ops-platform-dev
type: Opaque
data:
  basic-auth-password: c0d2WHVRbmVRa0w2V25DdA==
  mongo-express-admin-user: YWRtaW4=
  mongo-express-password: WUVYS3dRSkNwalptVHQ3Zw==
  mongodb-auth-password: enltMTIz
  site-cookie-secret: aDdkaG5aNXk0NDROOXE1YmZ4ZTBKZnpjY3laUXA4Vw==
  site-session-secret: d0pYTWNjSGNBZzNLZG0wanM5OEIxUFA3d0tDSm8=
