apiVersion: v1
kind: Secret
metadata:
    name: registry-puller
    namespace: ops-platform-dev
type: kubernetes.io/dockerconfigjson
data:
    .dockerconfigjson: ENC[AES256_GCM,data:cYN3+PpdDNim9p1Qv1jtkgH1ZB90ojjvPI/0zOTjDHAoM5crbyYpDdFiQJqYV4FnW378kWwUzEMP2TQ/uxR5yx1Niupd9IDjcHlpMyYAG4OmT+GAz83uIxBD2qFjigEle9D6hZA6yfmLFxZmS4C8DLkjLpP+ZRPz4qzv3IPYJm2fsNHJyw5YO5J5F999BO2+STHulbNPuioGS7ehzZRbGKYdTL8J8yNplshK4PJHjTdq94ic4TEP9s9kwzVWU56/MKeI7z6FpAzFgfm5/zvExUSf7nEcgDZSk82xW4mOjrHCB25D,iv:A0EqM5QJYzX+aJvyEFzRvwIQ9jK3FUVsDT1J4HdJS5Q=,tag:8s+/j8ZR2VjXJNc+Cw0UIQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsNi90VXo4T0theC9LKzQv
            T29kVWRIN1ZzWTkxSTZFaTQvUjJGK1V2K1YwCkVDNXBrSGdNLyszY0ZKWmJQVjRS
            WGhKYUR5WE9ja1Nsd2NrdU1LUEtUYWsKLS0tIGJMYjJIaFVKZjBaT3hiWGVrZzBZ
            V0Z0T2hNbEx1bnoxZ1NZT3JXRE5jcUkK2+VTutv5Jk8cfJ1BoyKlfE/XRwOBelzt
            ko6VTZoLGIQW8NhHlInAZHQZvOU3j93i3a9mi/fSxPdBkHEHFRnS6g==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1usl2cz5ltxz7au5tdpjqz7t77nzh3a29dgyewwfexqcctjfp2edq5yy6ge
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-05T16:24:51Z"
    mac: ENC[AES256_GCM,data:gkSiVGkCHVLg9dGnPjW/+Xpf0UvSKUbgps6FnOxHKxQWCrdmJTikbtf9FO0Rau46RWoWvoj/bKrX8UjKxfQfOHGUfhRCNrn5ojcRI0UFAXpYlqZXLyPP6A+Hjd6c7hDRe78jWyiXELe2A10hwQObAAyh/XAIh/dkeLT8xtq/tqA=,iv:Tdq/SQDBBfrJnYx1r/lRDCKHDG2akXxdG4WsnCrY6Fw=,tag:0QYPaH4JnTuCoTHyiUaXxw==,type:str]
    version: 3.13.3
