apiVersion: v1
kind: Secret
metadata:
  name: mongodb-llmopsservice-db-secret
  namespace: data-platform-dev
type: Opaque
data:
  DB_HOST: bW9uZ29kYi1zdW5tb29uYWkuZGF0YS1wbGF0Zm9ybS1kZXYuc3ZjLmNsdXN0ZXIubG9jYWw=
  DB_NAME: bGxtb3BzX2Ri
  DB_PORT: MjcwMTc=
  DB_SSLMODE: ZGlzYWJsZQ==
  DB_USER: c3VubW9vbmFpX2Rldg==

