apiVersion: v1
kind: Secret
metadata:
    name: knowledge-database-runtime
    namespace: app-platform-dev
stringData:
    DATABASE_URL: ENC[AES256_GCM,data:32269pkwGP6QKSDqE52bSb2V6O9aQFZh+ec8d2LE+NX4DwsoXGjk6OibQluipvho3U8OTqKmlRwTfy+CNTh85Y9JYnL1hTzwDZtQRl8/2d5b99YsHMBqH7Nj8/CF+I5WigeedncYfk9aSQi1QMXJ+bFzyUs8n1F4NEslVeVjJalUDM3vc623ug4wfiLz,iv:VAjEn7FdxuvaegCbh6PsYhZhg/KpL7vr7Ujc2XuSvM4=,tag:x3rOTKuJCOWgDFWFfv9A/A==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsRzMvMzl2WkRvZlBNUkFa
            THdQZkpVbmtDQWpTRERtSHlKU05QdDk5M1RzCjVjbitTNHo4TmdOYXE2eHZHQWhJ
            RGh1NHZQMGs2MWNmWUQwNzdHd3BjNlkKLS0tIGpZVzllbnNaSFZqQ3Y2Z1Jabncx
            eEpTVXVVWXVMejFRdm9CdGpscitKRE0KJjXkOFNsFZUSvTRgOElj295+4mJTmKog
            h4ZVkNSDpPnIWqQwvhrpmJ1DwqurdKTMqQE0XTjQUfGdXzUPtnvoVg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1usl2cz5ltxz7au5tdpjqz7t77nzh3a29dgyewwfexqcctjfp2edq5yy6ge
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-03T15:19:40Z"
    mac: ENC[AES256_GCM,data:ZyabOLhaVPQJ77g80hFVsBo6RP2r6oYDoPjeZ4UU15rKNOj/GIpr8Utlktd9mja9uPn1yNs6p6v3aH/HVe3ZuAP2NHQfriYsnYOqURgfYTqAG/f5t+AM6yS+W6jNCvbEH7hfRuy+nT3noX2QmHdp9upcU8soeY5AmhtSaw68v44=,iv:cfYlwuaqVPWVVvkRWnouqw+HY381SQNL3jvGTiJ6Jao=,tag:SO3ggxxC08GVcl5OAWmgRw==,type:str]
    version: 3.13.3
