apiVersion: v1
kind: Secret
metadata:
  name: celeryworker-tools-admin-backend-secret
  namespace: app-platform-dev
  labels:
    app: celeryworker-tools-admin-backend
    component: celery-worker
    backend: tools-admin-backend
type: Opaque
stringData:
  CELERY_BROKER_URL: "amqp://tools-admin-backend-worker:tools-admin-backend-worker-dev@rabbitmq-sunmoonai.messaging-platform-dev.svc.cluster.local:5672/tools-development"
  CELERY_RESULT_BACKEND: ""
