#!/usr/bin/env python3
"""Run only the pinned official config generator in a restricted offline container.

No install.sh, host-root mount, privileged mode, services, ports, network, deletion,
or automatic retries. Default prints the preparation plan. Local only; cloud 未经实机验证.
"""
import argparse
import copy
import hashlib
import io
import json
import os
from pathlib import Path, PurePosixPath
import subprocess
import tarfile

import yaml
from harbor_inputs import EXPECTED_ROOT, HERE, sha, write_new

NAME = 'sunmoon-harbor-2132-20260927-prepare'
TAG = 'sunmoon-offline/harbor-prepare:2.13.2-53905b30703f'


def command(args, timeout=30, output=None):
    if output:
        with output.open('xb') as stream:
            p = subprocess.run(args, stdout=stream, stderr=subprocess.STDOUT, timeout=timeout)
    else:
        p = subprocess.run(args, capture_output=True, timeout=timeout)
    if p.returncode:
        raise RuntimeError('Preparation command failed: '+args[0]+'; consult private logs')
    return p.stdout.decode() if not output else ''


def nested(installer):
    outer = tarfile.open(installer, 'r:gz')
    return outer, tarfile.open(fileobj=outer.extractfile('harbor/harbor.v2.13.2.tar.gz'), mode='r|gz')


def extract_prepare_archive(installer, target):
    outer, inner = nested(installer)
    with outer, inner:
        for item in inner:
            if item.name == 'manifest.json':
                manifests = json.load(inner.extractfile(item))
                break
        else:
            raise RuntimeError('No Docker archive manifest')
    chosen = [m for m in manifests if m.get('RepoTags') == ['goharbor/prepare:v2.13.2']]
    if len(chosen) != 1:
        raise RuntimeError('Expected one official prepare image')
    manifest = copy.deepcopy(chosen[0])
    wanted = {manifest['Config'], *manifest['Layers']}
    for name in wanted:
        if PurePosixPath(name).is_absolute() or '..' in PurePosixPath(name).parts:
            raise RuntimeError('Invalid image archive path')
    manifest['RepoTags'] = [TAG]
    found = set()
    image_config = None
    outer, inner = nested(installer)
    with outer, inner, tarfile.open(target, 'x') as output:
        for item in inner:
            if item.name not in wanted:
                continue
            if item.name in found or not item.isfile():
                raise RuntimeError('Unexpected image archive member')
            found.add(item.name)
            stream = inner.extractfile(item)
            if item.name == manifest['Config']:
                data = stream.read()
                image_config = json.loads(data)
                if hashlib.sha256(data).hexdigest() != '53905b30703f3c06f9123e431a89fae4c1cc4adb0371eac66c87839e8cc7d749':
                    raise RuntimeError('Prepare config digest mismatch')
                stream = io.BytesIO(data)
            output.addfile(item, stream)
        if found != wanted:
            raise RuntimeError('Incomplete prepare image archive')
        raw = json.dumps([manifest]).encode()
        member = tarfile.TarInfo('manifest.json')
        member.size = len(raw)
        output.addfile(member, io.BytesIO(raw))
    return image_config


def replace_env(path, mapping):
    lines = path.read_text().splitlines()
    for key, value in mapping.items():
        matches = [i for i, line in enumerate(lines) if line.startswith(key+'=')]
        if len(matches) != 1 or any(c in value for c in '\r\n\x00'):
            raise RuntimeError('Generated env key is absent/ambiguous or unsafe: '+key)
        lines[matches[0]] = key+'='+value
    path.write_text('\n'.join(lines)+'\n')


def patch_generated(root, receipt):
    cfg = root/'generated-config'
    value = lambda key: (root/'private'/key).read_text()
    shared = {'CORE_SECRET': value('core_secret'), 'JOBSERVICE_SECRET': value('jobservice_secret')}
    registry = {'REGISTRY_CREDENTIAL_USERNAME': value('registry_username'), 'REGISTRY_CREDENTIAL_PASSWORD': value('registry_password')}
    targets = [cfg/'core/env', cfg/'jobservice/env', cfg/'registryctl/env', cfg/'registry/config.yml', cfg/'registry/passwd']
    for path in targets:
        if not path.is_file() or path.is_symlink():
            raise RuntimeError('Expected generated config missing')
    # Preserve original generated bytes before the narrowly defined migration patch.
    for path in targets:
        write_new(root/'generated-before-migration'/path.relative_to(cfg), path.read_bytes())
    replace_env(cfg/'core/env', {**shared, **registry, 'CSRF_KEY': value('csrf_key'),
                               'POSTGRESQL_PASSWORD': value('database_password'), 'HARBOR_ADMIN_PASSWORD': value('admin_password')})
    replace_env(cfg/'jobservice/env', {**shared, **registry})
    replace_env(cfg/'registryctl/env', shared)
    registry_config = yaml.safe_load((cfg/'registry/config.yml').read_text())
    if registry_config['storage']['filesystem']['rootdirectory'] != '/storage':
        raise RuntimeError('Unexpected registry filesystem root')
    registry_config['http']['secret'] = value('registry_http_secret')
    registry_config['storage']['maintenance']['uploadpurging']['enabled'] = False
    registry_config['storage']['maintenance']['readonly'] = {'enabled': True}
    registry_config['storage']['delete']['enabled'] = False
    (cfg/'registry/config.yml').write_text(yaml.safe_dump(registry_config, sort_keys=False))
    (cfg/'registry/passwd').write_bytes((root/'private/registry_htpasswd').read_bytes())
    # Recompare all immutable original snapshots and preseeded encryption/signing keys.
    for name, info in receipt['private_files'].items():
        if sha(root/name) != info['sha256']:
            raise RuntimeError('Official generation changed a preserved private input: '+name)
    for relative, mapping in [('core/env', {**shared, **registry, 'CSRF_KEY': value('csrf_key')}),
                              ('jobservice/env', {**shared, **registry}), ('registryctl/env', shared)]:
        fields = dict(line.split('=', 1) for line in (cfg/relative).read_text().splitlines() if '=' in line)
        if any(fields.get(k) != v for k, v in mapping.items()):
            raise RuntimeError('Post-generation original credential check failed')
    compose = yaml.safe_load((root/'compose/docker-compose.yml').read_text())
    if 'postgresql' in compose['services'] or 'trivy-adapter' in compose['services']:
        raise RuntimeError('Unexpected bundled database or scanner activation in generated Compose')
    # Upstream Compose is evidence only; it retains broad ports/restart policies.
    return {'original_inputs_preserved': True, 'internal_credentials_restored': True,
            'registry_readonly': True, 'uploadpurging': False, 'registry_delete': False,
            'official_services': sorted(compose['services']), 'compose_runtime_admitted': False}


def main():
    os.umask(0o077)
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--installer', type=Path, required=True)
    parser.add_argument('--apply', action='store_true')
    parser.add_argument('--resume-import', action='store_true',
                        help='Resume only an imported image before any generator container exists')
    args = parser.parse_args()
    root = EXPECTED_ROOT
    if not args.apply:
        print(json.dumps({'dry_run': True, 'root': str(root), 'container': NAME,
            'image_import': 'one official prepare image under a unique local alias',
            'network': 'none', 'privileged': False, 'host_root_mount': False,
            'delete': False, 'start_harbor': False, 'runtime_compose_admitted': False}, indent=2))
        return
    if os.geteuid() != 0 or root.resolve() != root:
        raise RuntimeError('Root and nonsymlink admitted candidate path required')
    receipt = json.loads((root/'inputs-receipt.json').read_text())
    for name, info in receipt['private_files'].items():
        if sha(root/name) != info['sha256']:
            raise RuntimeError('Staged input changed; preserve and investigate')
    command(['bash', '/opt/sunmoon/admin/storage/storage-20260928-v3/check-storage-mounts.sh', '--layout', 'sunmoon-data',
             '--expected-uuid', receipt['site']['data_uuid'], '--min-free-gib', '40', '--require-service-visibility'])
    lock = json.loads((HERE/'artifacts.lock.json').read_text())['artifacts'][0]
    if args.installer.resolve() != args.installer or args.installer.stat().st_size != lock['bytes'] or sha(args.installer) != lock['sha256']:
        raise RuntimeError('Official installer checksum mismatch')
    if NAME in command(['docker', 'ps', '-a', '--format', '{{.Names}}']).splitlines():
        raise RuntimeError('Generator container already exists; no overwrite/retry')
    if (root/'compose/docker-compose.yml').exists() or (root/'generator-state.json').exists():
        raise RuntimeError('Generated Compose already exists')
    if args.resume_import:
        if not (root/'generated-config').is_dir() or any((root/'generated-config').iterdir()):
            raise RuntimeError('Resume requires an empty generated-config directory')
        with tarfile.open(root/'materials/prepare.tar') as archive:
            manifest = json.load(archive.extractfile('manifest.json'))
            if len(manifest) != 1 or manifest[0]['RepoTags'] != [TAG]:
                raise RuntimeError('Unexpected retained prepare archive')
            raw = archive.extractfile(manifest[0]['Config']).read()
            if hashlib.sha256(raw).hexdigest() != '53905b30703f3c06f9123e431a89fae4c1cc4adb0371eac66c87839e8cc7d749':
                raise RuntimeError('Retained prepare config digest mismatch')
            image_config = json.loads(raw)
    else:
        if command(['docker', 'image', 'ls', '--format', '{{.Repository}}:{{.Tag}}', TAG]).strip():
            raise RuntimeError('Private import alias already exists; inspect instead of overwrite')
        for name in ['materials', 'generated-config']:
            (root/name).mkdir(mode=0o700, exist_ok=False)
        image_config = extract_prepare_archive(args.installer, root/'materials/prepare.tar')
        command(['docker', 'load', '--input', str(root/'materials/prepare.tar')], timeout=180, output=root/'materials/load.log')
    image = json.loads(command(['docker', 'image', 'inspect', TAG]))[0]
    if image['RootFS']['Layers'] != image_config['rootfs']['diff_ids']:
        raise RuntimeError('Imported prepare layer identities mismatch')
    for key in ['Env', 'Entrypoint', 'Cmd', 'User', 'WorkingDir', 'Volumes']:
        actual, expected = image['Config'].get(key), image_config['config'].get(key)
        # Docker omits the archive's empty default User field; both mean root.
        if key == 'User':
            actual, expected = actual or '', expected or ''
        if actual != expected:
            raise RuntimeError('Imported prepare configuration mismatch: '+key)
    if image['Config'].get('Volumes') != {'/harbor_make': {}}:
        raise RuntimeError('Unexpected generator image volume declaration')
    mounts = [(root/'input', '/input', True), (root/'data', '/data', False),
              (root/'compose', '/compose_location', False), (root/'generated-config', '/config', False),
              (root/'private', '/hostfs'+str(root/'private'), True)]
    create = ['docker', 'create', '--name', NAME, '--label', 'sunmoonai.registry.config-generator=20260927',
              '--network=none', '--restart=no', '--pull=never', '--memory=1g', '--cpus=2', '--pids-limit=256',
              '--cap-drop=ALL', '--cap-add=CHOWN', '--cap-add=DAC_OVERRIDE', '--cap-add=FOWNER',
              '--security-opt=no-new-privileges', '--log-driver=none',
              '--tmpfs', '/harbor_make:rw,nosuid,nodev,size=16m']
    for src, dst, readonly in mounts:
        create += ['--mount', f'type=bind,src={src},dst={dst}'+(',readonly' if readonly else '')]
    create += [image['Id'], 'prepare']
    state = {'container_name': NAME, 'container_id': None, 'image_id': image['Id'], 'completed': False}
    write_new(root/'generator-state.json', (json.dumps(state, indent=2)+'\n').encode())
    container = command(create).strip()
    state['container_id'] = container
    (root/'generator-state.json').write_text(json.dumps(state, indent=2)+'\n')
    try:
        command(['docker', 'start', '--attach', container], timeout=180, output=root/'generator.log')
        status = json.loads(command(['docker', 'inspect', container]))[0]
        if status['State']['ExitCode'] != 0 or status['State']['Running']:
            raise RuntimeError('Official generator did not finish successfully')
        state['verification'] = patch_generated(root, receipt)
        state['completed'] = True
    finally:
        command(['docker', 'stop', '--time', '20', container], timeout=30)
        (root/'generator-state.json').write_text(json.dumps(state, indent=2)+'\n')
    print(json.dumps({'prepared': True, 'container_stopped': True, **state['verification']}, indent=2))


if __name__ == '__main__':
    try:
        main()
    except Exception as exc:
        message = str(exc) if isinstance(exc, RuntimeError) else type(exc).__name__+'; details withheld'
        raise SystemExit('[official-prepare] FAIL: '+message) from None
