apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata: {name: platform-services, namespace: flux-system}
spec:
  interval: 5m
  retryInterval: 30s
  timeout: 8m
  path: ./components/services/core
  sourceRef: {kind: OCIRepository, name: platform}
  prune: false
  deletionPolicy: Orphan
  wait: true
  decryption:
    provider: sops
    secretRef: {name: sops-age}
