apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq-auth-secret
  namespace: messaging-platform-dev
type: Opaque
data:
  rabbitmq-erlang-cookie: RVJMQU5HQ09PS0lFMTIzNDU2Nzg5MA==
  rabbitmq-password: enltMTIz
  rabbitmq-username: YWRtaW4=
