apiVersion: v1
kind: Secret
metadata:
    name: registry-puller
    namespace: ingress-system
type: kubernetes.io/dockerconfigjson
data:
    .dockerconfigjson: ENC[AES256_GCM,data:IkxjhBbzd5t/0lWLawr3GJs2sp1mFtFWDzvaku0ivKZu4g4w8YoE9s8C50pXFYM1l56Y648tKgwGnJu0CyaFy9iG3Gn2OBL73WIlHJMw19DZRN8hkjdzvsafYVoDO1cDePk+CcetcBg7QvaVNa6oru0UDSGvkzUJOirxSbdFCW/HdZTLfApJlecQgvOu8hu5BtC5COk+cM7TvpYjjUIo0WJhwKAzoO1e48zx6sa1dBR2Fo/tmI8zN0SPxZ2g7NEhjJCSWLevTbLgwlxFus/g/d5DMMmHCWIe7OtelT1BB8joh9KY,iv:29IIQv9kTqBQDTCljzgMxhR6GgFAlknuyzT+jGnzaX8=,tag:cxE/tlQCyDbLU7gq9hyO5w==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIT3NFUEROWi9jc01YTk5I
            Tk9ObC9XN2orZG5JZW96N2hESW5zVFBydGxzCnZNd3BSQjJIMlVTOWF2MTZrQnFL
            OUxpRW1RRDMza2FzbXhnRXE3V3pkTHcKLS0tIDBCY2pWWDZKUWJpaTRETktOTXBX
            SFNBZVZaZytxUG56TUdYV3hLL0h0b2sKKsoRByF4+/dnD2aBwY0pZtykPo3bIK4U
            jYt1mdaEiz4X1PcPG10JY3BHEKRegO7VZg6CkyzCEVeQdFTbu6xIxQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1usl2cz5ltxz7au5tdpjqz7t77nzh3a29dgyewwfexqcctjfp2edq5yy6ge
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-03T03:14:06Z"
    mac: ENC[AES256_GCM,data:4Hj88xMwTfdYIegWagWHlUKTinqDtsq5V3kXP2Ma0RwdR2o+keBTKGLtGEo6BNZAJmkJWhjwXVtIuTbAGg0lh0X+NGNurRJj/kkEWPr7dEv/fFy40prKFZIh9NrfM3gIkFb2Ptyw+kOBdTCui6U1aqg0kj7tOqfYcxJFL9QCjPo=,iv:bSnxES+cx0abIbz0AWx9p7hvjfW+L3CIvbZ+xC81Y1Y=,tag:doGLT/cagV0Vjtc3DNrU+Q==,type:str]
    version: 3.13.3
