apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - storage.yaml
  - data.yaml
  - network.yaml
  - ingress.yaml
  - postgresql-auth.sops.yaml
  - redis-auth.sops.yaml
  - rabbitmq-auth.sops.yaml
  - ingress-puller.sops.yaml
