apiVersion: v1
kind: Secret
metadata:
    name: postgresql-auth
    namespace: platform-system
stringData:
    password: ENC[AES256_GCM,data:3q9QDt/bjWwB2x3mJg==,iv:wn/Ogjqc/dWSc0h77E/xB8YU+X0LnGAIIg1rROldwgg=,tag:lgX11hzua+jWI+r+/CJ7cg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnV1hNYmQrbVV1WEJBN1lZ
            UUdQVFhxQnVyZTZ2YWdIS0JDb2c0bjRiMUJnCllxeWs1bitZRG9kN0lOMTh2M1p1
            NnVYeC81UnRtU25ObXJpK2xhNHlEYWMKLS0tIDNGZnFKY0JuKzViL2F6VVBGdUpP
            WUpPY1FINkNOTGN5ajlFaTdzV1VsR00K1+Jw0tZR0VDj7G9ldXWaWgZZBqxC8Yuo
            phpheqKaPYgrX4OuPIudvuapNZGxjmgFAf7SwucxhFfI/jdRNYVlZQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1usl2cz5ltxz7au5tdpjqz7t77nzh3a29dgyewwfexqcctjfp2edq5yy6ge
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-03T03:14:02Z"
    mac: ENC[AES256_GCM,data:vT7eAm3QCbgUSc2y2NXWblwlNf/ZbspnKgeWr+3gyD1jzzGVgdS5Z4oX7BX8bcKsr8/XJWt4gf244HPW+hXh8thY+mKNe3mcJtsUVpPol4/AtKn/0o+/XifsMAoM56JPHM62HVt3MifVk5cByYhWwjbNgRsqJRR+sV49C1b230k=,iv:J0qkvEOcOT1UJ138uulQaKb2MR4RjvbbHSK6FkNTyHM=,tag:xQOzFWWyEZEQyZKTbAYApA==,type:str]
    version: 3.13.3
