apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: llmops-app-bff-pvc
  namespace: ${NAMESPACE:-app-platform-dev}
  labels:
    app: llmops-app-bff
spec:
  accessModes:
    - ${PVC_ACCESS_MODE:-ReadWriteOnce}
  storageClassName: ${PVC_STORAGE_CLASS:-}
  resources:
    requests:
      storage: ${PVC_STORAGE_SIZE:-10Gi}
