apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tools-admin-backend-pvc
  namespace: app-platform-dev
  labels:
    app: tools-admin-backend
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 10Gi
