apiVersion: v1
kind: Secret
metadata:
    name: investment-domain-runtime
    namespace: app-platform-dev
stringData:
    WORKBENCH_CREDENTIAL_KEY: ENC[AES256_GCM,data:sJB77M5hIZ+VW+QeQ1t3nDh2UtQ+hbPWguetPAMYuIYP0CZvQ/9ndZa8yNk=,iv:GW9fjwhOLIZ/POmbsfSrosTcBhhNoTjX+edbXkqC5w0=,tag:eB3lhVlt5Ac41soKtso02w==,type:str]
    WORKBENCH_AGENT_PAIRING_HMAC_KEY: ENC[AES256_GCM,data:rTdn8BmPTTou7cqMkIZyLzoQVptVMLz4gejx7caT653buRL/pjxf9Q==,iv:CnEy7Yl4s5wz5wtNINmqySqpaJEU1TtK/rstksQPvaE=,tag:rpEDFnPnFyZ1JQO3tgUMqg==,type:str]
    WORKBENCH_PROVISIONER_TOKEN: ENC[AES256_GCM,data:4DY4xm1n7tZqMZ69hmSCL/DFvrA8F6BrrnqFiIhaYaX/pUM2ju8HPQ==,iv:R1BYTbTjNJQT+nP4qau1am1I5F1/x+lDsypi+2gkQrM=,tag:IrGCCXylZozseHP6vkVe/Q==,type:str]
    WORKBENCH_RELAY_ADMIN_TOKEN: ENC[AES256_GCM,data:IwGbh9xQ7zlAeW507VAbrIRnFyYQE8TmEtGjSPqIfUD+tx7h7beV6w==,iv:144zmxggdINbAfT0Jc4hfse7PhZiogHUNOedRXOZDbk=,tag:tlSJLXZ3d1ymdhjUcqHncg==,type:str]
    WORKBENCH_TOKEN_SIGNING_KEY: ENC[AES256_GCM,data:WCTebuHgFCf88ToYliUWpfgab0s7IRFx8BhmqzEI9+JdVWNnhVrWpD5HEnSkITAGsIX1cf0mXvI59bAJ7Cn4Vf3F6pLASRN3Ow7YTM33dY/zSqvA2WIYjr9VzJDWWJHWUjITMFeQBLVjUJPzWk2nSbmxi5IMOQ8L3/uWa0/FbspzOEbHyhgcVLUirp45owd6pHfSp8KfhPSsnMPMdbem6Cvyja9H8GxgFWwv432NtcJoY0fknLx7sBViPnwJT+kTLh463Pd+KY1aVLopC458Go/xkzgZUqp1Fre0BUVQlNuObiFxQwMJ7ozbTTk3k2HKmA==,iv:cLf0xuoN5GvyHveGpxzpkLKEauoWVe/+bBrT+an1GD8=,tag:/kppck+fcJRCtVAqRz2TjQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5RHA2ZEgxemlOYllacmpw
            ZEp0TUFKeTlHRmV4T2wvaHptWENvUERKeTJBCjVTUHdrM2dxKzJXdEJqR3A3Zjkz
            YmFFcFpKbDBJTFZDMnJIZkFFaG8zRmMKLS0tIEU0b2tOWlNMYkU1QUtWejhIbmV6
            Z0xyN0llWWpXd1NzUkJGTjUrUjZOK28KVPSm/rrLJT9N03LPCrAm1j+X4crb9BW2
            RraiZvzM4uZ+WHAQjwVzmHBIN+VawwVG6K/5i4Ljta4tvRqQ5w8k/A==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1usl2cz5ltxz7au5tdpjqz7t77nzh3a29dgyewwfexqcctjfp2edq5yy6ge
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-10T09:50:39Z"
    mac: ENC[AES256_GCM,data:2+UDwI5idQthBLUE6qrvR7fdOZyRqWpSxMeG4Q1TTL7KDTv+0wR9I2DNhwpqeJqyZhf9Hbl3FP2xrrz7OlGAjjFqpB7DjZOqx9oh5qO7PPMDFePZCghWT1BC2KHt1fF5fp+sIlvUM/++iQ52CuMgalJzIEGIuC0IKPVD23vZUK8=,iv:OBsLcQ2uwiANCvZyRMIU91QBVxGwL+2xX+k0N4ZtzSY=,tag:DIxGkyeV27nVM1YZDg8FAA==,type:str]
    version: 3.13.3
