apiVersion: v1
kind: Secret
metadata:
  name: document-converter-secret
  namespace: ${NAMESPACE}
  labels:
    app: document-converter
type: Opaque
stringData:
  # Sentry 监控
  SENTRY_DSN: "${SENTRY_DSN}"

