apiVersion: v1
kind: ConfigMap
metadata:
  name: research-web-frontend-config
  namespace: ${NAMESPACE}
  labels:
    app: research-web-frontend
data:
  NODE_ENV: "${NODE_ENV}"
  NEXT_PUBLIC_APP_NAME: "${NEXT_PUBLIC_APP_NAME}"
  NEXT_PUBLIC_API_URL: "${NEXT_PUBLIC_API_URL}"
