apiVersion: v1
kind: Secret
metadata:
  name: celeryworker-llm-admin-backend-secret
  namespace: app-platform-dev
  labels:
    app: celeryworker-llm-admin-backend
    component: celery-worker
    backend: llm-admin-backend
type: Opaque
stringData:
  CELERY_BROKER_URL: "amqp://llm-admin-backend-worker:llm-admin-backend-worker-dev@rabbitmq-sunmoonai.messaging-platform-dev.svc.cluster.local:5672/llm-development"
  CELERY_RESULT_BACKEND: ""
