apiVersion: v1
kind: Secret
metadata:
  name: celeryworker-research-admin-backend-secret
  namespace: app-platform-dev
  labels:
    app: celeryworker-research-admin-backend
    component: celery-worker
    backend: research-admin-backend
type: Opaque
stringData:
  CELERY_BROKER_URL: "amqp://research-admin-backend-worker:research-admin-backend-worker-dev@rabbitmq-sunmoonai.messaging-platform-dev.svc.cluster.local:5672/research-development"
  CELERY_RESULT_BACKEND: ""
