apiVersion: v1
kind: Secret
metadata:
  name: celeryworker-llm-web-backend-secret
  namespace: ${NAMESPACE:-app-platform-dev}
  labels:
    app: celeryworker-llm-web-backend
    component: celery-worker
    backend: llm-web-backend
type: Opaque
stringData:
  CELERY_BROKER_URL: "${CELERY_BROKER_URL}"
  CELERY_RESULT_BACKEND: "${CELERY_RESULT_BACKEND}"
