# Elasticsearch Kind 开发环境配置

global:
  kibanaEnabled: false
  defaultStorageClass: "local-path"
  imagePullSecrets:
    - name: "harbor-registry-secret"
  security:
    allowInsecureImages: true
  imageRegistry: "harbor.sunmoonai.com:30443"

clusterName: elasticsearch-dev

image:
  registry: harbor.sunmoonai.com:30443
  repository: k8s-images/elasticsearch
  tag: 9.1.2-debian-12-r0
  pullPolicy: IfNotPresent

master:
  image:
    registry: harbor.sunmoonai.com:30443
    repository: k8s-images/elasticsearch
    tag: 9.1.2-debian-12-r0
    pullPolicy: IfNotPresent

  masterOnly: false
  extraRoles:
    - data
    - ingest
  replicaCount: 1
  resourcesPreset: "small"
  resources:
    requests:
      cpu: 300m
      memory: 512Mi
    limits:
      cpu: 800m
      memory: 1Gi
  heapSize: 512m

  persistence:
    enabled: true
    size: 8Gi
    storageClass: "local-path"

data:
  image:
    registry: harbor.sunmoonai.com:30443
    repository: k8s-images/elasticsearch
    tag: 9.1.2-debian-12-r0
    pullPolicy: IfNotPresent
  replicaCount: 0
  resourcesPreset: "small"
  resources:
    requests:
      cpu: 300m
      memory: 512Mi
    limits:
      cpu: 800m
      memory: 1Gi
  heapSize: 512m
  persistence:
    enabled: false
    size: 20Gi
    storageClass: ""

coordinating:
  image:
    registry: harbor.sunmoonai.com:30443
    repository: k8s-images/elasticsearch
    tag: 9.1.2-debian-12-r0
    pullPolicy: IfNotPresent
  replicaCount: 0
  resourcesPreset: "small"
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 300m
      memory: 1Gi
  heapSize: 512m
  livenessProbe:
    enabled: true
    initialDelaySeconds: 120
    periodSeconds: 15
    timeoutSeconds: 5
    failureThreshold: 6
  readinessProbe:
    enabled: true
    initialDelaySeconds: 120
    periodSeconds: 10
    timeoutSeconds: 5
    failureThreshold: 12

ingest:
  replicaCount: 0

volumePermissions:
  enabled: true

service:
  type: ClusterIP
  ports:
    restAPI: 9200
    transport: 9300

security:
  enabled: true
  existingSecret: elasticsearch-secrets
  tls:
    restEncryption: true
    autoGenerated: true
    verificationMode: certificate

metrics:
  enabled: false

sysctlImage:
  enabled: true
  registry: harbor.sunmoonai.com:30443
  repository: k8s-images/os-shell
  tag: 12-debian-12-r51
