apiVersion: v1
kind: Secret
metadata:
    name: tpl-rabbitmq-provision
    namespace: messaging-platform-dev
stringData:
    password: ENC[AES256_GCM,data:72ixyvjbfyb2AtNGS/0SeGg5xovady7vjYCE2FJEVrXdc1unR4zRDw==,iv:fq3vmQ9NfT0h0fD9xBbngRUFZN8cw0mQQWDy4SlfatM=,tag:py4BZvDeYTWAtYOEJtLDWg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyQkt1dGhRdmd2YnJYSXhi
            cldteFBnM2FGcnNiZ0FVaVhoT2R1UlVDMUdrClVTNW1FazdxWVlzTHYrTnhDVzFh
            L0dYdFlVL1k1R2lOWGRaeld6K0RRcG8KLS0tIGxKZTNPMFNublJSaEtxM0lJK0lK
            VnBOUTU4UXhuUmx6MWZUMkVvNms3bUEKK93cEZH4SdQ2lNSZ5Ba5BkDL4WMRPgFw
            BltSO4fjC0flTTESW4jwuagwddQd0aVPnv/MGtBv+JUDeTYh2pMeSg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1usl2cz5ltxz7au5tdpjqz7t77nzh3a29dgyewwfexqcctjfp2edq5yy6ge
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-06T07:22:22Z"
    mac: ENC[AES256_GCM,data:fkCi5X2J2/eLJRMp+NMneTPauYCBPG/KS1xr3Crzzpn8KZLqLm3Ue69IGno4R2eCFXcZ21MNG6K5tq0/EOjwGvUhivCuR9lQlUIBiymGGY1hoLoMtFSWuameg8DBkL5Rf41JqV+jVTAhQO+MjNzo5RAfyIUXR0OjM85c27nUqvY=,iv:D2YMKMyHfLz6rGAdW7JzaVdEhYmavdrHCEEEKexshOU=,tag:nqDoKihV8IXZnEhvl73sRQ==,type:str]
    version: 3.13.3
