apiVersion: v1
kind: Secret
metadata:
    name: tpl-rabbitmq-runtime
    namespace: app-platform-dev
stringData:
    CELERY_BROKER_URL: ENC[AES256_GCM,data:3rUhTqjhuX0dIxSMZblpP9oBlWszJH05t0P5gg5NsrYjnzAumVP1VmvES3vK70jNwFW8cg4r9qVQkP4Dmt6jZL0i//rljOf+gUR4CG7Hou7GDm+hDAULCJiVFuznUBpvrbCkmZWxB8DcT8uxugYqhD3FlPsFzQ==,iv:M9/COqj3/Oruf6wf9y3/g5dY7HTZp7zE6NamkKnnLts=,tag:yXaP82rwEYkRkYZWqAw1wA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwQ09yOGlqdVprNFdQZC9s
            c0h3Q1h0aTZmNzdsTUVLWWlOSDV2eWwzbEhjCkNhNDluemgvcGlSWXRSYnZwZHhz
            cDBSNEVhV1VVUHd3b0Z2dnlnWW9PSXMKLS0tIDJoYlBidzNYWlRUbFNtNWJGcUZB
            SHZDUHJwQXB2R3RjRkhiZDg0aHlCcG8KNbpwoBnbsK4VhDuzffN77CQkSrrpdRTd
            wwMoX6fbQuiLijcWAd6sv7TkqFMo+G4R4NXRQXke3llyfR8CUfw7cA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1usl2cz5ltxz7au5tdpjqz7t77nzh3a29dgyewwfexqcctjfp2edq5yy6ge
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-06T07:22:23Z"
    mac: ENC[AES256_GCM,data:vOALR3+MJ4DNBRIuEr0iaebCaDc/oUZzantqiSr7BLj3q4kj4SoxwVnKwdDO3AnihOE9680PQbWuFFlgkuTpMXPawQ7Qzbngshf/T4+xWwb09tl9qhGTWGdbtxOLNxS+oOw3xbS7xRq21o08PGbpjp9R3QOx/lMqJMRUXlROnIs=,iv:srLVFMi94t3rKzJ3CD31zfGURyjWHC8Bl1hn6+opAS0=,tag:NvXvPi6xBt7JxI7mD1kkMQ==,type:str]
    version: 3.13.3
