# Incubator App BFF 中间件
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: incubator-app-bff-stripprefix
  namespace: {{NAMESPACE}}
  labels:
    app: app-platform-ingress
    component: incubator-app-bff
spec:
  stripPrefix:
    prefixes:
      - "/api/v1"

