apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: investment-web-backend-pvc
  namespace: app-platform-dev
  labels:
    app: investment-web-backend
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 10Gi
