apiVersion: v1
kind: PersistentVolume
metadata:
  name: rabbitmq-sunmoonai-dev-pv
spec:
  capacity:
    storage: 8Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: ""  # 静态 PV，不走 nfs-2 动态存储
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: 172.28.46.235
    path: /data/kind-nfs/messaging-platform-dev-data-rabbitmq-sunmoonai-0-pvc-7245a48e-73a1-4d6a-a1bb-cbb8600bf385
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rabbitmq-sunmoonai-dev-pvc
  namespace: messaging-platform-dev
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
  storageClassName: ""
  volumeName: rabbitmq-sunmoonai-dev-pv

