apiVersion: v1
kind: Secret
metadata:
  name: harbor-registry-secret
  namespace: data-platform-dev
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: eyJhdXRocyI6eyJoYXJib3Iuc3VubW9vbmFpLmNvbTozMDQ0MyI6eyJ1c2VybmFtZSI6ImFkbWluIiwicGFzc3dvcmQiOiJIYXJib3JAMTIzNDUiLCJhdXRoIjoiWVdSdGFXNDZTR0Z5WW05eVFERXlNelExIn19fQ==
