apiVersion: v1
kind: Secret
metadata:
  name: harbor-registry-secret
  namespace: app-platform-dev
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: eyJhdXRocyI6eyJoYXJib3Iuc3VubW9vbmFpLmNvbTozMDQ0MyI6eyJ1c2VybmFtZSI6ImFkbWluIiwicGFzc3dvcmQiOiJUT0RPX0ZJTExfSU5fSEFSQk9SX1BBU1NXT1JEIiwiYXV0aCI6IllXUnRhVzQ2VkU5RVQxOUdTVXhNWDBsT1gwaEJVa0pQVWw5UVFWTlRWMDlTUkE9PSJ9fX0=
