apiVersion: v1
kind: Secret
metadata:
  name: harbor-registry-secret
  namespace: ${NAMESPACE}
  labels:
    app: document-converter
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: "${HARBOR_DOCKER_CONFIG_JSON}"

