apiVersion: v1
kind: Secret
metadata:
    name: knowledge-rabbitmq-provision
    namespace: messaging-platform-dev
stringData:
    password: ENC[AES256_GCM,data:iCeic9ItEZcNsOXPi2pWLgLrT34lPUtnFxDNn/l3+Knl3AOQKGBMRg==,iv:ceoFqo+9RHczfSC6jrChzW7Of+d2gxRvgMMExzrTly0=,tag:iFcXg5h7Q1+gLPhFevx5Mw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtQ3VNa2IyWG8rdGpERk1t
            aUNyVDBwYXlkYmNMUTFMM0pTQjRqcmsyN2xFCkVLMVNYZlRvblJraHFkNTlkMHdq
            RlFKS2Flekg0Nnd1UHIzeFZhV2dRbVUKLS0tIGZlWVF0Zmljc1VNT3RiYlpPSkhh
            OEt5dDB0ZWwxYjJxZC9ZQVFoOE02ZTgKPoEuSOKroRhB01E3iUsDljT/lo8yNH2g
            5IGRhw18MibklY5zmTkfjGrT+aALZecaZv5gAWEGPhfSE9LWpE6bgQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1usl2cz5ltxz7au5tdpjqz7t77nzh3a29dgyewwfexqcctjfp2edq5yy6ge
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-03T15:19:45Z"
    mac: ENC[AES256_GCM,data:jnMCPBI1diTPfPXuimAyzAmjE7ZY2PG+YFldUMTiqctKZQD4+Yedk8nHJ4AEGvVVGoD6TRLunj2A0xARyN7+8L1tXR487hOOFJ5Bii4zJoDMmxeDDTGdtt5toYUX63l73+J6vz1be1R0/Gv4U/GwOGuyM3vLL+ntlct6s7wl5cc=,iv:9TivqLhhTcP58YlFYhfphnXmoXZ5QYnEvYUsH733YP0=,tag:3kqmoxYJK+boEQ0PThypwg==,type:str]
    version: 3.13.3
