PROJECT_ID="${PROJECT_ID:-sunmoonai}"
NAMESPACE="${NAMESPACE:-app-platform-dev}"
ENVIRONMENT="${ENVIRONMENT:-development}"

# 组件开关与优先级
incubator_ssr_config_enabled="${incubator_ssr_config_enabled:-true}"
incubator_ssr_config_priority="${incubator_ssr_config_priority:-500}"

incubator_ssr_secret_enabled="${incubator_ssr_secret_enabled:-true}"
incubator_ssr_secret_priority="${incubator_ssr_secret_priority:-600}"

