apiVersion: v1
kind: Secret
metadata:
  name: elasticsearch-myapp-secret
  namespace: data-platform-dev
type: Opaque
data:
  ENABLED: dHJ1ZQ==
  ES_HOST: ZWxhc3RpY3NlYXJjaC1zdW5tb29uYWkuZGF0YS1wbGF0Zm9ybS1kZXYuc3ZjLmNsdXN0ZXIubG9jYWw=
  ES_PASSWORD: enltMTIz
  ES_PORT: OTIwMA==
  ES_TLS: ZmFsc2U=
  ES_USERNAME: ZWxhc3RpYw==
  RESTART_COMPONENTS: ZmFsc2U=
