apiVersion: v1
kind: PersistentVolume
metadata:
  name: sunmoon-kind-casdoor
  annotations:
    sunmoonai.com/storage-owner: sunmoon-kind
    kustomize.toolkit.fluxcd.io/prune: disabled
spec:
  capacity: {storage: 1Gi}
  accessModes: [ReadWriteOnce]
  volumeMode: Filesystem
  persistentVolumeReclaimPolicy: Retain
  storageClassName: sunmoon-static
  local:
    path: /data/kind-local-storage/casdoor
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values: [sunmoon-kind-worker]
  claimRef:
    namespace: app-platform-dev
    name: casdoor-data
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: casdoor-data
  namespace: app-platform-dev
  annotations:
    kustomize.toolkit.fluxcd.io/prune: disabled
spec:
  accessModes: [ReadWriteOnce]
  storageClassName: sunmoon-static
  volumeName: sunmoon-kind-casdoor
  resources:
    requests: {storage: 1Gi}
