PROJECT_ID="${PROJECT_ID:-sunmoonai}"
NAMESPACE="${NAMESPACE:-app-platform-dev}"
ENVIRONMENT="${ENVIRONMENT:-development}"

llmops_ssr_config_enabled="${llmops_ssr_config_enabled:-true}"
llmops_ssr_config_priority="${llmops_ssr_config_priority:-500}"

llmops_ssr_secret_enabled="${llmops_ssr_secret_enabled:-true}"
llmops_ssr_secret_priority="${llmops_ssr_secret_priority:-600}"
